language: rust
rust: stable
cache: cargo
sudo: false
git:
  depth: 1
before_install:
 - chmod +x ci/install-tools.sh
before_script:
  - ci/install-tools.sh
script:
  - ci/run-all.sh
after_success:
  - ci/upload-docs.sh
