[package]
name = "PokemonBattleArena"
version = "0.1.0"
authors = ["lukav"]

[dependencies]
csv = "0.14"
enum_primitive = "0.1"
num = "0.1"
rand = "0.3"
rustc-serialize = "0.3.22"
regex = "0.2"
time = "0.1"
piston_window = "0.62.0"
